### ISSUE TITLE
Could you turn this into a tutorial?

### ISSUE THREAD

**Issue by tipsy** [ricardobaumann/real-time-statistics#1]
This looks like a neat project @ricardobaumann. I'm currently looking for a few more in-depth tutorials for Javalin, and this project seems like it could be a good fit. Are you interested in writing a tutorial for the project to be published on javalin.io ?

**Comment by ricardobaumann** [comment]
Hello @tipsy. Sorry for the late reply. Sure, I will take a look on it

**Comment by ricardobaumann** [comment]
Hello again @tipsy . How can we proceed to this tutorial? What format do you think we could use?

**Comment by tipsy** [comment]
It's great that you're interested! The source code for javalin.io is here: https://github.com/javalin/javalin.github.io
It's a jekyll-project, and all the tutorials are written in markdown. The type of markdown is identical to the markdown used on GitHub, so if you don't want to setup jekyll locally you can create a tutorial in this repo and use the preview function while working on it.

The tutorial should start with a short description of what the reader will learn (and a screenshot of the application if possible). Then you go through the source code and explain the choices you made.

**Comment by ricardobaumann** [comment]
ok, @tipsy. Its on the backlog :)

**Comment by ricardobaumann** [comment]
done

**Comment by tipsy** [comment]
Great, thank you!
